<?php

include_once("lib/GeometryLoader.class.php");
include_once("lib/adapters/GeoJSON.class.php");
include_once("lib/adapters/GeoJSON_Adapter.class.php");
include_once("lib/adapters/GeoJSON_Adapter_Doctrine.class.php");
include_once("lib/adapters/WKT.class.php");
include_once("lib/geometry/Geometry.class.php");
include_once("lib/geometry/Point.class.php");
include_once("lib/geometry/Collection.class.php");
include_once("lib/geometry/LineString.class.php");
include_once("lib/geometry/MultiPoint.class.php");
include_once("lib/geometry/LinearRing.class.php");
include_once("lib/geometry/Polygon.class.php");
include_once("lib/geometry/MultiLineString.class.php");
include_once("lib/geometry/MultiPolygon.class.php");
include_once("lib/geometry/GeometryCollection.class.php");

